import { User, Patient, Appointment, MedicalRecord, Invoice, DashboardStats } from './types';
import { ROLES, APPOINTMENT_STATUS, PATIENT_STATUS, BILLING_STATUS } from './constants';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@medicore.com',
    role: ROLES.DOCTOR,
    department: 'Cardiology',
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@medicore.com',
    role: ROLES.DOCTOR,
    department: 'Neurology',
  },
  {
    id: '3',
    name: 'Emily Davis',
    email: 'emily.davis@medicore.com',
    role: ROLES.RECEPTIONIST,
  },
  {
    id: '4',
    name: 'Admin User',
    email: 'admin@medicore.com',
    role: ROLES.ADMIN,
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: 'John Smith',
    age: 45,
    gender: 'Male',
    bloodGroup: 'O+',
    phone: '+1-555-0101',
    email: 'john.smith@email.com',
    address: '123 Main St, New York, NY 10001',
    emergencyContact: '+1-555-0102 (Jane Smith)',
    medicalHistory: ['Hypertension', 'Type 2 Diabetes'],
    status: PATIENT_STATUS.ACTIVE,
    registrationDate: '2024-01-15',
  },
  {
    id: 'P002',
    name: 'Maria Garcia',
    age: 32,
    gender: 'Female',
    bloodGroup: 'A+',
    phone: '+1-555-0201',
    email: 'maria.garcia@email.com',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    emergencyContact: '+1-555-0202 (Carlos Garcia)',
    medicalHistory: ['Asthma'],
    status: PATIENT_STATUS.ACTIVE,
    registrationDate: '2024-02-20',
  },
  {
    id: 'P003',
    name: 'Robert Johnson',
    age: 58,
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '+1-555-0301',
    email: 'robert.j@email.com',
    address: '789 Pine Rd, Chicago, IL 60601',
    emergencyContact: '+1-555-0302 (Lisa Johnson)',
    medicalHistory: ['Heart Disease', 'High Cholesterol'],
    status: PATIENT_STATUS.ACTIVE,
    registrationDate: '2023-11-10',
  },
  {
    id: 'P004',
    name: 'Emily Williams',
    age: 28,
    gender: 'Female',
    bloodGroup: 'AB+',
    phone: '+1-555-0401',
    email: 'emily.w@email.com',
    address: '321 Elm St, Houston, TX 77001',
    emergencyContact: '+1-555-0402 (David Williams)',
    medicalHistory: [],
    status: PATIENT_STATUS.ACTIVE,
    registrationDate: '2024-03-05',
  },
  {
    id: 'P005',
    name: 'James Brown',
    age: 65,
    gender: 'Male',
    bloodGroup: 'O-',
    phone: '+1-555-0501',
    email: 'james.brown@email.com',
    address: '654 Maple Dr, Phoenix, AZ 85001',
    emergencyContact: '+1-555-0502 (Mary Brown)',
    medicalHistory: ['Arthritis', 'Hypertension'],
    status: PATIENT_STATUS.ARCHIVED,
    registrationDate: '2023-08-22',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'A001',
    patientId: 'P001',
    patientName: 'John Smith',
    doctorId: '1',
    doctorName: 'Dr. Sarah Johnson',
    department: 'Cardiology',
    date: '2025-10-20',
    time: '09:00',
    duration: 30,
    status: APPOINTMENT_STATUS.SCHEDULED,
    reason: 'Routine checkup',
  },
  {
    id: 'A002',
    patientId: 'P002',
    patientName: 'Maria Garcia',
    doctorId: '2',
    doctorName: 'Dr. Michael Chen',
    department: 'Neurology',
    date: '2025-10-20',
    time: '10:30',
    duration: 45,
    status: APPOINTMENT_STATUS.SCHEDULED,
    reason: 'Headache consultation',
  },
  {
    id: 'A003',
    patientId: 'P003',
    patientName: 'Robert Johnson',
    doctorId: '1',
    doctorName: 'Dr. Sarah Johnson',
    department: 'Cardiology',
    date: '2025-10-19',
    time: '14:00',
    duration: 30,
    status: APPOINTMENT_STATUS.COMPLETED,
    reason: 'Follow-up appointment',
    notes: 'Patient condition improving',
  },
  {
    id: 'A004',
    patientId: 'P004',
    patientName: 'Emily Williams',
    doctorId: '2',
    doctorName: 'Dr. Michael Chen',
    department: 'Neurology',
    date: '2025-10-21',
    time: '11:00',
    duration: 30,
    status: APPOINTMENT_STATUS.SCHEDULED,
    reason: 'Initial consultation',
  },
  {
    id: 'A005',
    patientId: 'P001',
    patientName: 'John Smith',
    doctorId: '1',
    doctorName: 'Dr. Sarah Johnson',
    department: 'Cardiology',
    date: '2025-10-18',
    time: '15:30',
    duration: 30,
    status: APPOINTMENT_STATUS.CANCELLED,
    reason: 'Routine checkup',
    notes: 'Patient requested rescheduling',
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'MR001',
    patientId: 'P001',
    patientName: 'John Smith',
    doctorId: '1',
    doctorName: 'Dr. Sarah Johnson',
    date: '2025-10-19',
    diagnosis: 'Hypertension - Well Controlled',
    symptoms: ['High blood pressure', 'Occasional headaches'],
    prescriptions: [
      {
        id: 'RX001',
        medication: 'Lisinopril',
        dosage: '10mg',
        frequency: 'Once daily',
        duration: '30 days',
        instructions: 'Take in the morning with water',
      },
      {
        id: 'RX002',
        medication: 'Aspirin',
        dosage: '81mg',
        frequency: 'Once daily',
        duration: '30 days',
        instructions: 'Take with food',
      },
    ],
    labResults: [
      {
        id: 'LAB001',
        testName: 'Blood Pressure',
        value: '130/85',
        unit: 'mmHg',
        normalRange: '120/80',
        status: 'Normal',
      },
      {
        id: 'LAB002',
        testName: 'Blood Sugar',
        value: '110',
        unit: 'mg/dL',
        normalRange: '70-100',
        status: 'Abnormal',
      },
    ],
    notes: 'Patient responding well to current medication. Continue monitoring blood sugar levels.',
    attachments: [
      {
        id: 'ATT001',
        name: 'ECG_Report.pdf',
        type: 'application/pdf',
        size: 245000,
        uploadedAt: '2025-10-19T14:30:00Z',
        url: '/attachments/ecg_report.pdf',
      },
    ],
    version: 1,
    updatedBy: 'Dr. Sarah Johnson',
    updatedAt: '2025-10-19T15:00:00Z',
  },
  {
    id: 'MR002',
    patientId: 'P002',
    patientName: 'Maria Garcia',
    doctorId: '2',
    doctorName: 'Dr. Michael Chen',
    date: '2025-10-15',
    diagnosis: 'Migraine',
    symptoms: ['Severe headache', 'Sensitivity to light', 'Nausea'],
    prescriptions: [
      {
        id: 'RX003',
        medication: 'Sumatriptan',
        dosage: '50mg',
        frequency: 'As needed',
        duration: '30 days',
        instructions: 'Take at onset of migraine',
      },
    ],
    labResults: [],
    notes: 'Prescribed medication for migraine management. Follow-up in 2 weeks.',
    attachments: [],
    version: 1,
    updatedBy: 'Dr. Michael Chen',
    updatedAt: '2025-10-15T11:45:00Z',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'INV001',
    patientId: 'P001',
    patientName: 'John Smith',
    date: '2025-10-19',
    dueDate: '2025-11-03',
    items: [
      {
        id: 'ITEM001',
        description: 'Consultation - Cardiology',
        quantity: 1,
        unitPrice: 150,
        total: 150,
      },
      {
        id: 'ITEM002',
        description: 'ECG Test',
        quantity: 1,
        unitPrice: 100,
        total: 100,
      },
      {
        id: 'ITEM003',
        description: 'Blood Test',
        quantity: 1,
        unitPrice: 50,
        total: 50,
      },
    ],
    subtotal: 300,
    tax: 30,
    total: 330,
    status: BILLING_STATUS.PAID,
    paymentMethod: 'Credit Card',
    paidAt: '2025-10-19',
  },
  {
    id: 'INV002',
    patientId: 'P002',
    patientName: 'Maria Garcia',
    date: '2025-10-15',
    dueDate: '2025-10-30',
    items: [
      {
        id: 'ITEM004',
        description: 'Consultation - Neurology',
        quantity: 1,
        unitPrice: 150,
        total: 150,
      },
    ],
    subtotal: 150,
    tax: 15,
    total: 165,
    status: BILLING_STATUS.PENDING,
  },
  {
    id: 'INV003',
    patientId: 'P003',
    patientName: 'Robert Johnson',
    date: '2025-09-20',
    dueDate: '2025-10-05',
    items: [
      {
        id: 'ITEM005',
        description: 'Consultation - Cardiology',
        quantity: 1,
        unitPrice: 150,
        total: 150,
      },
      {
        id: 'ITEM006',
        description: 'Stress Test',
        quantity: 1,
        unitPrice: 250,
        total: 250,
      },
    ],
    subtotal: 400,
    tax: 40,
    total: 440,
    status: BILLING_STATUS.OVERDUE,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalPatients: 245,
  activePatients: 198,
  todayAppointments: 12,
  pendingInvoices: 8,
  monthlyRevenue: 45600,
  patientGrowth: 12.5,
  appointmentGrowth: 8.3,
  revenueGrowth: 15.2,
};

export const mockAppointmentChartData = {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  datasets: [
    {
      label: 'Appointments',
      data: [12, 19, 15, 22, 18, 8, 5],
      backgroundColor: 'rgba(59, 130, 246, 0.5)',
      borderColor: 'rgba(59, 130, 246, 1)',
      borderWidth: 2,
    },
  ],
};

export const mockRevenueChartData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  datasets: [
    {
      label: 'Revenue',
      data: [35000, 38000, 42000, 41000, 45000, 48000],
      backgroundColor: 'rgba(34, 197, 94, 0.5)',
      borderColor: 'rgba(34, 197, 94, 1)',
      borderWidth: 2,
    },
  ],
};

export const mockDepartmentChartData = {
  labels: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'General Medicine'],
  datasets: [
    {
      label: 'Patients by Department',
      data: [45, 38, 32, 28, 52],
      backgroundColor: [
        'rgba(59, 130, 246, 0.8)',
        'rgba(34, 197, 94, 0.8)',
        'rgba(251, 191, 36, 0.8)',
        'rgba(239, 68, 68, 0.8)',
        'rgba(168, 85, 247, 0.8)',
      ],
    },
  ],
};
